### ISSUE TITLE
Nightly builds failing for several months

### ISSUE THREAD

**Issue by erogluorhan** [ProjectPythia/radar-cookbook#137]
**What happened**:

Dear authors (cc'ing @mgrover1 and @brian-rose as you have the two largest contributions), the nightly builds of this cookbook have been failing for the last several months. 

Could you please have a look at it?

**Minimal Complete Verifiable Example**:

[Latest nightly build](https://github.com/ProjectPythia/radar-cookbook/actions/runs/11376137843/job/31648109675) as of the creation of this issue.

**Anything else we need to know?**:

If you think it is due to Pythia infrastructure or something else other than the cookbook itself, please let us know.

**Comment by brian-rose** [comment]
It's failing upon trying to 
```
import pyart
```

I was able to reproduce this behavior locally in a freshly created environment. I assume it's because of some package version inconsistencies in the environment. That's as far as I've dug so far.

**Comment by brian-rose** [comment]
I also got the same failure in a "plain pyart" environment by doing this:
```
mamba create --name pyart-test arm_pyart -c conda-forge
conda activate pyart-test
python -c "import pyart"
```

The import error is coming from xradar (a dependency of pyart), and is related to the recent [merging of DataTree into Xarray](https://docs.xarray.dev/en/stable/whats-new.html#v2024-10-0-oct-24th-2024).

The solved environment has the latest `xarray 2024.10.0` and `xradar 0.6.5` which are incompatible. Something is going wrong with the conda environment description for pyart. That's probably a solvable problem. But it might be moot.

I see that the xradar folks are close to releasing a version compatible with the latest xarray (https://github.com/openradar/xradar/issues/223) so I think it the best choice for now is to do nothing and allow upstream to catch up.

@mgrover1

**Comment by mgrover1** [comment]
Yes - there are some compatibility issues we are currently sorting through. We are working on resolving this ASAP, thank you for raising this to our attention

**Comment by kmuehlbauer** [comment]
If you are in need of testing: Please pin xradar to 0.7.0 (it will have a pin for xarray <= 2024.9.0.

When xradar is capable of supporting xarray >= 2024.10.0 we'll release xradar 0.8.0 (which should be out next week, Nov 4th/5th latest).

**Comment by kmuehlbauer** [comment]
@clyne Could you point me to some resources of that meeting? Interested in the particular issues there. Thanks!

**Comment by brian-rose** [comment]
Quick update here, xradar 0.8.0 is now released with compatibility with the latest xarray and datatree. We are still failing on `import pyart` for now. Looks like there's some progress on pyart compatibility here: https://github.com/ARM-DOE/pyart/pull/1681

**Comment by kmuehlbauer** [comment]
@brian-rose Pinning xradar to 0.7.0 and xarray to <=2024.9.0 should get you going until the party issues are sorted out.

**Comment by mgrover1** [comment]
@kmuehlbauer @brian-rose - I am looking at this today and will be cutting a new release of Py-ART that should solve this problem! Thank you for raising the issue and your patience here.

**Comment by erogluorhan** [comment]
@mgrover1, looks like the latest [nightly build](https://github.com/ProjectPythia/radar-cookbook/actions/runs/11788470857) from yesterday still failed but the build issues now seems to be due to a FileNotFound error if you'd like to have a look into it.

**Comment by mgrover1** [comment]
After a bit of debugging and the merging of #139 , looks like things are building again 👍
